### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/common/collect/EmptyImmutableList$1

### ISSUE THREAD

**Issue by juniorlimajj** [alexkasko/windows-service-installer#3]
I'm getting this error when I run `mvn clean insall`

```
Exception in thread "Thread-6" java.lang.NoClassDefFoundError: com/google/common/collect/EmptyImmutableList$1
        at com.google.common.collect.ImmutableList.of(ImmutableList.java:68)
        at com.google.common.collect.ImmutableList.copyFromCollection(ImmutableList.java:294)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:260)
        at ru.concerteza.util.concurrency.CallableList.call(CallableList.java:45)
        at ru.concerteza.util.concurrency.CallableList.call(CallableList.java:19)
        at ru.concerteza.util.concurrency.CtzConcurrencyUtils$CallableWrapper.run(CtzConcurrencyUtils.java:35)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.EmptyImmutableList$1
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 7 more
```

**Comment by mehmetkemalbayer** [comment]
Same here.
